permalink: /blog/:title
url: http://markmiyashita.com
paginate: 10000
lsi: true
pygments: true
markdown: rdiscount
title: Mark Miyashita
author:
    name: Mark Miyashita
    email: negativetwelve@gmail.com
    gihub: negativetwelve
    twitter: negativetwelve