permalink: /:categories/:title
url: http://markmiyashita.com
destination: _deploy
pygments: true
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, rakefile, readme.md, LICENSE]
title: Mark Miyashita
author:
    name: Mark Miyashita
    email: negativetwelve@gmail.com
    gihub: negativetwelve
    twitter: negativetwelve

current_semester: fa13

cs61a_categories:
  basics: [su13, fa13]
  higher_order_functions: [sp13, su13]

work:
  - name: Yelp
    role: Software Engineering Intern - Mobile Team
    start-date: "May '13"
    end-date: "Present"
    image: /public/images/yelp.png
    modal: yelp
    description: As an intern on the Mobile Team, I built a flow analysis tool that allows you to breakdown and visualize user flows from the app. It also enables a visual interface for A/B testing and breakdown of data by dimensions. Gave a technical presentation to all of Yelp Engineering about the architecture of my project and how to extend it. I also worked on improving performance for some of our back-end processing, worked with analytics on the mobile apps, and added a few minor features to the iOS app.
    full-description:

  - name: UC Berkeley
    role: Undergraduate Student Instructor for CS61A
    start-date: "Jan. '13"
    end-date: "Present"
    image: /public/images/berkeley.png
    modal: cs61a-ta
    description: I am an Undergraduate Student Instructor for the introductory computer science course, CS61A at UC Berkeley. I teach two sections, hold office hours, prepare discussion notes, create labs, and also lead review sessions. My TA ratings are located <a href="https://hkn.eecs.berkeley.edu/coursesurveys/instructor/7419">here.</a>
    full-description:

  - name: Kloudless
    role: Software Engineer
    start-date: "Dec. '12"
    end-date: "May '13"
    image: /public/images/kloudless.png
    modal: kloudless
    description: I worked on adding automation for attachments by adding a stream that listens for new emails and then processes a set of user-defined rules. The stream is an abstraction for Storm, a distributed realtime computation system.
    full-description:

  - name: Inigral Inc.
    role: Software Engineer Intern
    start-date: "Jul. '12"
    end-date: "Dec. '12"
    image: /public/images/inigral.png
    modal: inigral
    description: I worked on both the front and back-end of Inigral's large scale Rails app. On the back-end, I worked to optimize database queries as well as fix bugs that involved the administrative panels. On the front-end, I fixed several issues dealing with the appearance of the communities pages.
    full-description:

  - name: UC Berkeley
    role: CS10 Head Reader
    start-date: "Aug. '12"
    end-date: "Dec. '12"
    image: /public/images/berkeley.png
    modal: cs10-reader
    description: As the Head Reader for the undergraduate course CS10, I not only grade homework, projects, and exams, but also work with Professor Dan Garcia to deal with logistics and delegation of work among the readers.
    full-description:

  - name: UC Berkeley SA-IT
    role: Residential Computing Consultant
    start-date: "May '12"
    end-date: "May '13"
    image: /public/images/rescomp.png
    modal: rescomp
    description: I provide technical support and customer service on topics such as computer software, security, and general hardware configurations for all students living in university-owned housing. I also lead workshops geared towards teaching students about being safe on the web.
    full-description:

  - name: UC Berkeley
    role: CS61A Reader
    start-date: "May '12"
    end-date: "Dec. '12"
    image: /public/images/berkeley.png
    modal: cs61a-reader
    description: This semester, working with Professor John DeNero, my job is to focus on coding style within projects. I help students become both precise and concise in their code while still keeping it readable and manageable.
    full-description:

  - name: Mac Hints from BinaryAge
    role: Website Developer/Editor
    start-date: "Feb. '12"
    end-date: "May '13"
    image: /public/images/binaryage.png
    modal: binaryage
    description: I develop and maintain a subsection of the website BinaryAge.com. I designed the layout and contribute articles every week. Over 290,000 views since I began developing in March of 2012. Average of 1,500 views a day/45,000 views a month.
    full-description:

projects:
  - name: Pound Pong
    url:
    repo: https://github.com/negativetwelve/ping-pong-ipad
    image:
    modal: pound-pong
    description: Initially, the idea started out as a web app that would keep track of all of the Ping Pong matches that went on at the Yelp office. However, the project quickly transitioned into much more. Using an RFID scanner hooked up to an Arduino which is hooked up to the iPad, we can communicate with the application using our badges which all happen to be RFID. From there, we can 'badge' into our matches and record the winner in a seamless transaction using nothing more than our badges and a single tap to label the winner. Results are sent to a simple Flask server through a JSON API where they are stored in a Mongo Database. This was a project that I worked on with a group of 4 at our semi-annual Yelp hackathon. We had two people working on the Flask server / front-end of the website and two of us (including me) working on the iPad app and getting it to communicate with the RFID scanner.

  - name: iOS (currently unnamed) game with JSON API
    url: 
    repo: 
    modal: 
    description: I've been working on an iOS game that has a Rails JSON backend and will eventually have a web component too. Promo video and web page coming soon.

  - name: Global Snapshot
    url: http://globalsnapshot.herokuapp.com/
    repo: https://github.com/japhethwong/global-snapshot
    image: 
    modal: global-snapshot
    description: Working on a group of three at the LinkedIn Hack Day 2013, we buit a realtime Twitter and Flickr visualizer. Watch as tweets and photos fall onto the map and as the photos form a realtime stream on the sidebar. Want to see more photos? Simply expand the sidebar by pressing the toggle button on the bottom right. Hover over any of the dots to view the tweet or photo from that location. Node.js backend while working with several APIs including Google Maps, Twitter Realtime, and Flickr Realtime. Also uses Socket.io for sending the data to the browser in realtime.

  - name: Calaborate
    url: http://calaborate.herokuapp.com
    repo: https://github.com/negativetwelve/calaborate
    image: /public/images/calaborate.png
    modal: calaborate
    description: I worked as the lead developer on a small team to develop a tool for Cal students to create meetups and study sessions to review for midterms and finals.

  - name: Appsearch.es
    url: http://appsearch.es
    repo: https://github.com/negativetwelve/appsearches
    image: /public/images/appsearches.png
    modal: appsearches
    description: An iOS app search engine. Data is gathered using a scrapper that I built and stored in a Postgres database. Search is done by indexing the database and using Postgres built-in full-text search.

  - name: Rubik's Detection
    url:
    repo: https://github.com/negativetwelve/rubiks_detection
    image:
    modal: rubiks-detection
    description: The idea was simple, take a web camera, use it to detect the colors of a rubik's cube that a user holds up to the screen. Analyze the colors, pass the output to a solver and display the necessary steps to solve the cube. It actually worked and we won third place at a hackathon as a result. My main role was working on detecting the colors by holding up the rubik's cube to your screen.

  - name: Sound of Dub
    url: https://intense-journey-6792.herokuapp.com/
    repo: https://github.com/negativetwelve/sound-of-dub
    image: /public/images/sound-of-dub.png
    modal: sound-of-dub
    description: A music app that I built at a hackathon. It utilizes the Soundcloud API and allows users to make and play their own playlists.

  - name: Tim Todo
    url: https://timtodo.herokuapp.com/
    repo: https://github.com/negativetwelve/Tim
    image: /public/images/tim.png
    modal: tim
    description: A vim-style web based todo app that I built with a friend at our first ever hackathon. We won the Hilfinger Award given to us by Box at the 2012 H@B Hackjam.

  - name: markmiyashita.com
    url: http://markmiyashita.com
    repo: https://github.com/negativetwelve/markmiyashita.com
    image: /public/images/website.png
    modal: markmiyashita
    description: My personal about me website that I have developed from scratch. It is built using Jekyll and hosted on Github Pages.

  - name: Life Logger
    url: 
    repo: https://github.com/negativetwelve/facebook-hackathon
    image: /public/images/life-logger.png
    modal: life-logger
    description: I worked with a team of four at the 2012 Battle of the Bay Facebook Hackathon. We built an event logger for your computer that allows you to visualize and analyze your habits on the computer.

  - name: Pets Alliance
    url:
    repo: https://github.com/negativetwelve/pets-alliance
    image: /public/images/petsalliance.png
    modal: petsalliance
    description: Half of an MMORPG that I built in the summer of 2012. The UI was never finished but the backend worked pretty well. May continue this project in the future.

  - name: bashprofile.com
    url: http://bashprofile.com
    repo: https://github.com/negativetwelve/bashprofile.com
    image: /public/images/bashprofile.png
    modal: bashprofile
    description: A small tech blog that I built and designed.

