permalink: /:categories/:title
url: http://markmiyashita.com
destination: _deploy
pygments: true
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, rakefile, readme.md, LICENSE]
title: Mark Miyashita
author:
  name: Mark Miyashita
  email: negativetwelve@gmail.com
  gihub: negativetwelve
  twitter: negativetwelve
