current_semester: fa13

cs_classes:
  cs61a:
    basics:
      semesters: [base, su13, fa13]
      problems:
        - name: "What Are Functions?"
          file: what_are_functions
          type: Warmup
          tags: [functions]
          semesters:
            - base:
                date: "2013-06-15"
                published: true
                solution: true
              su13:
                date: "2013-06-15"
                published: true
                solution: true
              fa13:
                date: "2013-08-15"
                published: true
                solution: true

      notes:
        - name: "Getting Started with Python"
          file: getting_started_with_python
          tags: [functions, variables]
          semesters:
            - base:
                date: "2013-05-14"
                published: true
              su13:
                date: "2013-05-14"
                published: true
              fa13:
                date: "2013-08-15"
                published: true
    functions:
      semesters: []
    control:
      semesters: []
    higher_order_functions:
      semesters: [base, sp13, su13]
    environment_diagrams:
      semesters: []
    lambdas:
      semesters: []
    newtons_method:
      semesters: []
    recursion:
      semesters: [base, sp13, su13]
      problems:
        - name: "Sum Digits"
          file: sum_digits
          type: Warmup
          tags: [iteration, math]
          semesters:
            - base:
                date: "2013-02-18"
                published: true
                solution: true
              sp13:
                date: "2013-02-18"
                published: true
                solution: true
              su13:
                date: "2013-07-03"
                published: true
                solution: true
    rlists:
      semesters: [base, sp13]
    data_abstraction:
      semesters: []
    iterables:
      semesters: []
    object_oriented_programming:
      semesters: [base, sp13]
    dictionaries:
      semesters: [base, sp13]
    mutable_data:
      semesters: [base, sp13]
    inheritance:
      semesters: [base, sp13]
    generic_functions:
      semesters: [base, sp13]
    orders_of_growth:
      semesters: [base, sp13]
    tree_recursion:
      semesters: [base, sp13]
    memoization:
      semesters: [base, sp13]
    functional_programming:
      semesters: []
    scheme:
      semesters: []
    exceptions:
      semesters: []
    interpreters:
      semesters: []
    tail_recursion:
      semesters: []
    streams:
      semesters: []
    generators:
      semesters: []
    iterators:
      semesters: []
    declarative_programming:
      semesters: []
    logic:
      semesters: [base, sp13]
    unification:
      semesters: []
    mapreduce:
      semesters: []
    parallelism:
      semesters: []
  cs61b:
    basics:
      semesters: [base]
      notes:
        - name: "Getting Started with Java"
          file: getting_started_with_java
          tags: [classes, types]
          semesters:
            - base:
                date: "2013-08-20"
                published: true
    linked_list:
      semesters: []
  cs61c:
  cs70:
  cs170:
  cs188:
